---
version: '3.9'

networks:
  default:
    name: egi
    driver: bridge

volumes:
  certificates:
  logs:

services:
  # ************************
  # IMS Tools components
  # ************************
  # SSL terminator
  ssl:
    container_name: ism-ssl
    image: egi/ism-ssl:latest
    build:
      context: ssl/
      args:
        - SERVICE_DOMAIN=${SERVICE_DOMAIN}
        - SERVICE_EMAIL=${SERVICE_EMAIL}
        - SERVICE_UI=ui:8081
        - SERVICE_SLM=slm-api:8081
        - GRAFANA_URL=http://grafana:3000
        - TELEMETRY_URL=${OTEL_COLLECTOR_ADDR}
        - CORS_ORIGINS=${CORS_ORIGINS:-.*}
        - CORS_HEADERS=${CORS_HEADERS:-Origin,Content-Type,Accept}
        - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
    links:
      - ui
      - slm-api
      - grafana
    volumes:
      - certificates:/etc/letsencrypt
    healthcheck:
      test: ['CMD', '/opt/status.sh']
      start_period: 30s
      interval: 1m
      timeout: 5s
    restart: unless-stopped
    ports:
      - "80:80"
      - "${SERVICE_PORT}:443"
      - "${TELEMETRY_PORT}:8080"

  # Frontend
  ui:
    container_name: ism-ui
    image: egi/ism-ui:latest
    build:
      context: ../frontend/
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - slm-api

  # SLM API
  slm-api:
    container_name: slm-api
    image: egi/ism-slm-api:latest
    build:
      context: ../backend/service-level-management/src/main/docker
    environment:
      - EGI_CHECKIN_PASSWORD=${EGI_CHECKIN_PASSWORD}
      - QUARKUS_OIDC_CREDENTIALS=${QUARKUS_OIDC_CREDENTIALS}
      - QUARKUS_LOG_FILE_PATH=/deployments/logs/slm-api.json
      - QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
      - QUARKUS_OPENTELEMETRY_TRACER_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES},service.name=data-transfer
      - QUARKUS_HTTP_CORS_ORIGINS=/${CORS_ORIGINS:-.*}/
      - QUARKUS_HTTP_CORS_HEADERS=${CORS_HEADERS:-Origin,Content-Type,Accept}
      - QUARKUS_HTTP_CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
    volumes:
      - logs:/deployments/logs:rw
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - otelcol

  # ************************
  # Telemetry components
  # ************************
  # Jaeger (traces)
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "${JAEGER_SERVICE_PORT}:16686" # Jaeger UI
      - "${JAEGER_COLLECTOR_PORT}:4317"

  # Loki (logs)
  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    volumes:
      - ./loki/loki.yaml:/etc/loki/local-config.yaml
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped
    ports:
      - "${LOKI_COLLECTOR_PORT}:3100"

  # Prometheus (metrics)
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "${PROMETHEUS_SERVICE_PORT}:9090"

  # Grafana (dashboard)
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 75M
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  # OpenTelemetry collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
      - logs:/usr/logs/egi-ism:ro
    ports:
      - "${OTEL_COLLECTOR_PORT}:4317"
      - "9464:9464"   # Prometheus exporter
      - "8888:8888"   # Metrics endpoint
      - "13133:13133" # Health check
    depends_on:
      - jaeger
